### ISSUE TITLE
fields not explained

### ISSUE THREAD

**Issue by ghost** [icclab/disco-dashboard#1]
Section:disco-dashboard/setup_guide.md
after running `bundle exec figaro install`:

```
development:
  # DISCO endpoint (e.g. 'http://127.0.0.1:8080/disco/')
  disco_ip: 'http://xxx.xxx.xxx.xxx:port/disco/' 
  # external_network: name of the network with connection to the outside internet
  external_network: '<external_net>'
  # App needs a fingerprint of the keypairs generated by DISCO framework to not load those keypairs.
  # The one below was used when this setup guide was written. 
  # In case it is outdated, you need to update it.
  fingerprint: "b2:c1:f1:50:e3:f8:7b:88:fa:e3:b1:97:a5:6b:32:27"
```

disco_ip: sometimes the port is 8080 and sometimes 8888 Is there any recommendations?
What is external_network? can we have an example

Thank you
